name: SonarCloud Analysis

on: [push]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache SonarCloud packages 
      uses: actions/cache@v2
      with:
        path: |
          ~/.sonar/cache 
          ~/.sonar/native-sonar-scanner
        key: ${{ runner.os }}-sonar
        restore-keys: |
          ${{ runner.os }}-sonar

    - name: Check commit message
      run: |
        
          echo "Run make for building";
          make build-test; # Adjust this line based on your Makefile
          make test-run
          ./gradlew sonarqube \
            -Dsonar.organization=KingVentrix007 \
            -Dsonar.projectKey=KingVentrix007_Memory-Allocator \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }};
       
